site_name: Gen AI RAG LangChain
site_description: A comprehensive Python project for Gen AI RAG with LangChain
site_author: Your Name
site_url: https://github.com/shyenuganti/gen_ai_rag_langchain

repo_name: shyenuganti/gen_ai_rag_langchain
repo_url: https://github.com/shyenuganti/gen_ai_rag_langchain
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            merge_init_into_class: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference:
    - Core: api/core.md
    - Configuration: api/config.md
    - CLI: api/cli.md
    - API: api/api.md
  - Deployment:
    - Local Development: deployment/local.md
    - Docker: deployment/docker.md
    - AWS ECS: deployment/aws-ecs.md
  - Testing: testing.md
  - Contributing: contributing.md
  - Changelog: changelog.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shyenuganti/gen_ai_rag_langchain
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/gen-ai-rag-langchain/
